### LISTAR TODOS
GET https://localhost:7256/company


###
GET https://localhost:7256/company/1


### NOVA EMPRESA
POST https://localhost:7256/company
Content-Type: application/json

{
    "Name": "x",
    "Phone": "123",
    "Address": {
        "ZipCode": "85814-518",
        "Street": "Rua Apolonia Vedana",
        "Number": "1661",
        "Neighborhood": "Floresta",
        "City": "Cascavel",
        "CountryCode": "",
        "Complement": ""
    },
    "Employes":[
        {
            "name": "xx",
            "salary": 1050000,
            "role":{
                "Id": 1
            }
        }
    ]
}

###
POST https://localhost:7256/company
Content-Type: application/json

{
    "name": "aaa",
    "phone": "999999999",
    "address": {
        "zipCode": "85814518",
        "street": "Rua Apolonia Vedana",
        "number": "123",
        "neighborhood": "Floresta",
        "city": "Cascavel",
        "state": "PR"
    }
}


###
PUT https://localhost:7256/company
Content-Type: application/json

{
    "Id": 1,
    "Name": "Empresa Teste 1",
    "Phone": "1234"
}


###
DELETE https://localhost:7256/company/1