GET https://localhost:7256/company


###
GET https://localhost:7256/company/1


###
POST https://localhost:7256/company
Content-Type: application/json

{
    "Name": "Empresa 1",
    "Phone": "123",
    "Address": {
        "ZipCode": "85814-518",
        "Street": "Rua Apolonia Vedana",
        "Number": "1661",
        "Neighborhood": "Floresta",
        "City": "Cascavel",
        "CountryCode": "",
        "Complement": ""
    },
    "Employes":[
        {
            "Name": "Empregado 1",
            "Salary": 10500,
            "Role":{
                "Id": 1,
                "Name": "Programador"
            }
        }
    ]
}


###
PUT https://localhost:7256/company
Content-Type: application/json

{
    "Id": 1,
    "Name": "Empresa Teste 1",
    "Phone": "1234"
}


###
DELETE https://localhost:7256/company/1